### ISSUE TITLE
Pre-run Check does not give useful error on failure

### ISSUE THREAD

**Issue by MattArceri** [Peter-Simpson/ConformU#1]
While testing my implementation I had forgotten to implement 'atpark'. This meant that when ConformU started the Pre-run Check it tried to get 'atpark' and was given a reply stating that it wasn't implemented. Instead of indicating this it just reported the following with no usable information 
`12:23:37.743 PreRunCheck                         ISSUE    Exception when testing device: Unsupported command
12:23:37.744 
12:23:37.744 ConformanceCheck                             Further tests abandoned.`

For seemingly everything else mandatory that the tool tests it would report something along the lines of `ISSUE    This member is mandatory but threw a PropertyNotImplementedException exception, it must function per the ASCOM specification.`

I'm suggesting it be changed to give a similar error prior to abandoning the test if 'atpark' isn't supported.

**Comment by Peter-Simpson** [comment]
Hi Matt,

Thanks for reporting this issue. I've added improved error handling and reporting for all interface calls in the Telescope Pre-run checks. I've also updated the original Conform code with the same fixes.

Best wishes, Peter
