### ISSUE TITLE
RightAscensionRate test 

### ISSUE THREAD

**Issue by charleslemaire0** [Peter-Simpson/ConformU#11]
Hello  Peter

Here a small issue:

When CanSetRightAscensionRate  is true and CanSetDeclinationRate is false, the rate test routines tries anyway to set DeclinationRate in the write RightAscensionRate test routine, and report an false positive issue.

attached you can find the log

Thanks for your time and great work, this tool has so much value!

12:45:57.347 ASCOM Universal Device Conformance Checker Version 2.0.1.23374, Build time: Sat 30 December 2023 14:28:12
12:45:57.384 
12:45:57.400 Operating system is Microsoft Windows 10.0.19045 64bit, Application is 64bit.
12:45:57.441 
12:45:57.444 COM Driver ProgID: ASCOM.TeenAstro.Telescope
12:45:57.448 
12:45:57.469 CreateDevice                        INFO     Creating NATIVE COM device: ASCOM.TeenAstro.Telescope
12:45:57.651 CreateDevice                        INFO     Successfully created driver
12:45:58.674 CreateDevice                        OK       Driver instance created successfully
12:45:58.675 
12:45:58.676 Connect to device
12:45:58.680 InterfaceVersion                             About to get property InterfaceVersion
12:45:58.694 Connected                                    About to set Connected property
12:45:58.761 Connect                                      About to get Connected property
12:45:58.772 Connected                           OK       Connected to device successfully using Connected = True
12:45:58.773 
12:45:58.781 Common Driver Methods
12:45:58.781 InterfaceVersion                    OK       3
12:45:58.784 Connected                                    About to get property Connected
12:45:58.789 Connected                           OK       True
12:45:58.791 Description                                  About to get property Description
12:45:58.803 Description                         OK       TeenAstro Telescope
12:45:58.804 DriverInfo                                   About to get property DriverInfo
12:45:58.809 DriverInfo                          OK       Version: 1.5
12:45:58.809 DriverVersion                                About to get property DriverVersion
12:45:58.814 DriverVersion                       OK       1.5
12:45:58.815 Name                                         About to get property Name
12:45:58.821 Name                                OK       TeenAstro
12:45:58.821 
12:45:58.821 Action                              INFO     Conform cannot test the Action method
12:45:58.822 SupportedActions                             About to call method SupportedActions
12:45:58.847 SupportedActions                    OK       Found action: AutoAlign
12:45:58.868 
12:45:58.868 DeviceState                         INFO     DeviceState tests omitted - DeviceState is not available in this interface version.
12:45:58.871 
12:45:58.872 Can Properties
12:45:58.880 CanFindHome                                  About to get CanFindHome property
12:45:58.891 CanFindHome                         OK       True
12:45:58.900 CanPark                                      About to get CanPark property
12:45:58.914 CanPark                             OK       True
12:45:58.917 CanPulseGuide                                About to get CanPulseGuide property
12:45:58.929 CanPulseGuide                       OK       True
12:45:58.931 CanSetDeclinationRate                        About to get CanSetDeclinationRate property
12:45:58.947 CanSetDeclinationRate               OK       False
12:45:58.948 CanSetGuideRates                             About to get CanSetGuideRates property
12:45:58.954 CanSetGuideRates                    OK       True
12:45:58.956 CanSetPark                                   About to get CanSetPark property
12:45:58.962 CanSetPark                          OK       True
12:45:58.974 CanSetPierSide                               About to get CanSetPierSide property
12:45:58.993 CanSetPierSide                      OK       True
12:45:59.005 CanSetRightAscensionRate                     About to get CanSetRightAscensionRate property
12:45:59.023 CanSetRightAscensionRate            OK       True
12:45:59.024 CanSetTracking                               About to get CanSetTracking property
12:45:59.028 CanSetTracking                      OK       True
12:45:59.028 CanSlew                                      About to get CanSlew property
12:45:59.034 CanSlew                             OK       True
12:45:59.034 CanSlewltAz                                  About to get CanSlewAltAz property
12:45:59.041 CanSlewltAz                         OK       True
12:45:59.042 CanSlewAltAzAsync                            About to get CanSlewAltAzAsync property
12:45:59.049 CanSlewAltAzAsync                   OK       True
12:45:59.050 CanSlewAsync                                 About to get CanSlewAsync property
12:45:59.061 CanSlewAsync                        OK       True
12:45:59.063 CanSync                                      About to get CanSync property
12:45:59.071 CanSync                             OK       True
12:45:59.072 CanSyncAltAz                                 About to get CanSyncAltAz property
12:45:59.077 CanSyncAltAz                        OK       True
12:45:59.078 CanUnPark                                    About to get CanUnPark property
12:45:59.180 CanUnPark                           OK       True
12:45:59.181 
12:45:59.189 Pre-run Checks
12:45:59.195 Mount Safety                                 About to get AtPark property
12:45:59.461 Mount Safety                        INFO     Scope is not parked, continuing testing
12:45:59.509 Mount Safety                                 About to set Tracking property true
12:45:59.585 Mount Safety                        INFO     Scope tracking has been enabled
12:45:59.628 TimeCheck                           INFO     PC Time Zone:  (UTC+01:00) Brussels, Copenhagen, Madrid, Paris offset: 1 hours.
12:45:59.632 TimeCheck                           INFO     PC UTCDate:    01-Jan-2024 11:45:59.628
12:45:59.636 TimeCheck                                    About to get UTCDate property
12:45:59.683 TimeCheck                           INFO     Mount UTCDate: 01-Jan-2024 11:46:00.000
12:45:59.688 
12:45:59.692 Properties
12:45:59.727 TargetDeclination Read                       About to get TargetDeclination property
12:45:59.757 TargetRightAscension Read                    About to get TargetRightAscension property
12:45:59.771 AlignmentMode                                About to get AlignmentMode property
12:45:59.790 AlignmentMode                       OK       GermanPolar
12:45:59.790 Altitude                                     About to get Altitude property
12:45:59.813 Altitude                            OK       +43:43:23.0
12:45:59.821 ApertureArea                                 About to get ApertureArea property
12:45:59.837 ApertureArea                        OK       Optional member returned a PropertyNotImplementedException (COM Error: 0x80040400) error.
12:45:59.864 ApertureDiameter                             About to get ApertureDiameter property
12:45:59.872 ApertureDiameter                    OK       Optional member returned a PropertyNotImplementedException (COM Error: 0x80040400) error.
12:45:59.873 AtHome                                       About to get AtHome property
12:45:59.890 AtHome                              OK       False
12:45:59.896 AtPark                                       About to get AtPark property
12:45:59.911 AtPark                              OK       False
12:45:59.911 Azimuth                                      About to get Azimuth property
12:45:59.923 Azimuth                             OK       +04:59:04.0
12:45:59.924 Declination                                  About to get Declination property
12:45:59.949 Declination                         OK       +85:00:01.0
12:45:59.950 DeclinationRate Read                         About to get DeclinationRate property
12:45:59.963 DeclinationRate Read                OK       0.00
12:45:59.963 DeclinationRate Write                        About to set DeclinationRate property to 0.0
12:45:59.994 DeclinationRate Write               ISSUE    Unexpected error - CanSetDeclinationRate is False: Set DeclinationRate via :SXRd,0 has failed
12:45:59.995 DoesRefraction Read                          About to DoesRefraction get property
12:46:00.094 DoesRefraction Read                 OK       True
12:46:00.094 DoesRefraction Write                         About to set DoesRefraction property false
12:46:00.184 DoesRefraction Write                OK       Can set DoesRefraction to False
12:46:00.185 EquatorialSystem                             About to get EquatorialSystem property
12:46:00.190 EquatorialSystem                    OK       Topocentric
12:46:00.190 FocalLength                                  About to get FocalLength property
12:46:00.197 FocalLength                         OK       Optional member returned a PropertyNotImplementedException (COM Error: 0x80040400) error.
12:46:00.198 GuideRateDeclination Read                    About to get GuideRateDeclination property
12:46:00.271 GuideRateDeclination Read           OK       0.004178 (+00:00:15.0)
12:46:00.294 GuideRateDeclination Read                    About to set GuideRateDeclination property to 0.004178074605555556
12:46:00.330 GuideRateDeclination Write          OK       Can write Declination Guide Rate OK
12:46:00.347 GuideRateRightAscension Read                 About to get GuideRateRightAscension property
12:46:00.370 GuideRateRightAscension Read        OK       0.004178 (+00:00:15.0)
12:46:00.371 GuideRateRightAscension Read                 About to set GuideRateRightAscension property to 0.004178074605555556
12:46:00.396 GuideRateRightAscension Write       OK       Can set RightAscension Guide OK
12:46:00.400 IsPulseGuiding                               About to get IsPulseGuiding property
12:46:00.412 IsPulseGuiding                      OK       False
12:46:00.424 RightAscension                               About to get RightAscension property
12:46:00.459 RightAscension                      OK       +03:14:08.08
12:46:00.461 RightAscensionRate Read                      About to get RightAscensionRate property
12:46:00.495 RightAscensionRate Read             OK       0.10
12:46:00.504 RightAscensionRate Write            INFO     Configured offset test duration: 10 seconds.
12:46:00.512 RightAscensionRate Write                     Set rate to 0.0 - About to get Slewing property
12:46:00.531 RightAscensionRate Write                     Set rate to 0.0 - About to get Slewing property
12:46:00.546 RightAscensionRate Write                     Set rate to 0.0 - About to set RightAscensionRate property to 0
12:46:01.571 RightAscensionRate Write                     Set rate to 0.0 - About to get RightAscensionRate property
12:46:01.582 RightAscensionRate Write                     Set rate to 0.0 - About to get the Slewing property
12:46:01.591 RightAscensionRate Write            OK       Set rate to 0.0 - successfully set rate to 0
12:46:01.592 RightAscensionRate Write                     Set rate to 0.1 - About to get Slewing property
12:46:01.604 RightAscensionRate Write                     Set rate to 0.1 - About to get Slewing property
12:46:01.616 RightAscensionRate Write                     Set rate to 0.1 - About to set RightAscensionRate property to 0.1
12:46:02.662 RightAscensionRate Write                     Set rate to 0.1 - About to get RightAscensionRate property
12:46:02.671 RightAscensionRate Write                     Set rate to 0.1 - About to get the Slewing property
12:46:02.690 RightAscensionRate Write            OK       Set rate to 0.1 - successfully set rate to 0.1
12:46:02.720 RightAscensionRate Write -9.0                About to get SiteLatitude property
12:46:02.731 RightAscensionRate Write -9.0                About to get SiteLongitude property
12:46:02.744 RightAscensionRate Write -9.0                About to get SiteElevation property
12:46:02.814 SlewScope                                    About to set Tracking property to true
12:46:02.863 SlewScope                                    About to call SlewToCoordinatesAsync method, RA: +03:18:39.33, Declination: +85:00:00.0
12:46:02.946 Hour angle -9.00                             About to get Slewing property multiple times
12:46:07.983 SlewScope                                    About to get SideOfPier
12:46:08.000 SlewScope                                    About to get SideOfPier property
12:46:08.016 RightAscensionRate Write -9.0                About to get SideOfPier property
12:46:08.046 RightAscensionRate Write -9.0                About to get RightAscension property
12:46:08.054 RightAscensionRate Write -9.0                About to get Declination property
12:46:08.062 RightAscensionRate Write -9.0                About to set RightAscensionRate property
12:46:08.069 RightAscensionRate Write -9.0                About to set DeclinationRate property
12:46:08.092 RightAscensionRate Write            ISSUE    Unexpected error - CanSetRightAscensionRate is True: Set DeclinationRate via :SXRd,0 has failed

**Comment by Peter-Simpson** [comment]
Hi Charles,

Thanks for reporting this issue. I've revised the tests to omit testing an axis rate offset if the associated CanXXX method is false.

Please can you let me know whether this new version fixes the issue. [ConformU v 2.0.1 RC 8](https://download.ascom-standards.org/beta/ConformU(2.0.1-rc.8+23508)Setup.exe) 

Best wishes, Peter

**Comment by charleslemaire0** [comment]
It works!

**Comment by Peter-Simpson** [comment]
Great thanks for letting me know!

Best wishes, Peter
