### ISSUE TITLE
Abortslew check when Canslew is false

### ISSUE THREAD

**Issue by charleslemaire0** [Peter-Simpson/ConformU#13]
Hello,
TeenAstro can be configure as pure PUSH-TO telescope. I set in my driver Canslew to false when the telescope is configured as PUSH-TO
but I get this message in the U conform:

15:06:30.390 ASCOM Universal Device Conformance Checker Version 2.1.0.23787, Build time: Thu 11 January 2024 11:25:50
15:06:30.413 
15:06:30.414 Operating system is Microsoft Windows 10.0.19045 64bit, Application is 64bit.
15:06:30.414 
15:06:30.415 COM Driver ProgID: ASCOM.TeenAstro.Telescope
15:06:30.422 
15:06:30.428 CreateDevice                        INFO     Creating NATIVE COM device: ASCOM.TeenAstro.Telescope
15:06:30.776 CreateDevice                        INFO     Successfully created driver
15:06:31.803 CreateDevice                        OK       Driver instance created successfully
15:06:31.806 
15:06:31.809 Connect to device
15:06:31.814 InterfaceVersion                             About to get property InterfaceVersion
15:06:31.898 Connected                                    About to set Connected property
15:06:31.955 Connect                                      About to get Connected property
15:06:31.964 Connected                           OK       Connected to device successfully using Connected = True
15:06:31.969 
15:06:31.980 Common Driver Methods
15:06:31.981 InterfaceVersion                    OK       3
15:06:31.989 Connected                                    About to get property Connected
15:06:31.993 Connected                           OK       True
15:06:31.995 Description                                  About to get property Description
15:06:32.008 Description                         OK       TeenAstro Telescope
15:06:32.010 DriverInfo                                   About to get property DriverInfo
15:06:32.022 DriverInfo                          OK       Version: 1.5
15:06:32.025 DriverVersion                                About to get property DriverVersion
15:06:32.036 DriverVersion                       OK       1.5
15:06:32.041 Name                                         About to get property Name
15:06:32.046 Name                                OK       TeenAstro
15:06:32.047 
15:06:32.048 Action                              INFO     Conform cannot test the Action method
15:06:32.048 SupportedActions                             About to call method SupportedActions
15:06:32.076 SupportedActions                    OK       Found action: AutoAlign
15:06:32.079 
15:06:32.088 DeviceState                         INFO     DeviceState tests omitted - DeviceState is not available in this interface version.
15:06:32.092 
15:06:32.095 Can Properties
15:06:32.107 CanFindHome                                  About to get CanFindHome property
15:06:32.114 CanFindHome                         OK       False
15:06:32.123 CanPark                                      About to get CanPark property
15:06:32.160 CanPark                             OK       False
15:06:32.161 CanPulseGuide                                About to get CanPulseGuide property
15:06:32.171 CanPulseGuide                       OK       False
15:06:32.174 CanSetDeclinationRate                        About to get CanSetDeclinationRate property
15:06:32.187 CanSetDeclinationRate               OK       False
15:06:32.192 CanSetGuideRates                             About to get CanSetGuideRates property
15:06:32.203 CanSetGuideRates                    OK       False
15:06:32.207 CanSetPark                                   About to get CanSetPark property
15:06:32.221 CanSetPark                          OK       False
15:06:32.226 CanSetPierSide                               About to get CanSetPierSide property
15:06:32.234 CanSetPierSide                      OK       True
15:06:32.243 CanSetRightAscensionRate                     About to get CanSetRightAscensionRate property
15:06:32.255 CanSetRightAscensionRate            OK       False
15:06:32.256 CanSetTracking                               About to get CanSetTracking property
15:06:32.278 CanSetTracking                      OK       False
15:06:32.279 CanSlew                                      About to get CanSlew property
15:06:32.298 CanSlew                             OK       False
15:06:32.307 CanSlewltAz                                  About to get CanSlewAltAz property
15:06:32.320 CanSlewltAz                         OK       False
15:06:32.324 CanSlewAltAzAsync                            About to get CanSlewAltAzAsync property
15:06:32.342 CanSlewAltAzAsync                   OK       False
15:06:32.345 CanSlewAsync                                 About to get CanSlewAsync property
15:06:32.359 CanSlewAsync                        OK       False
15:06:32.360 CanSync                                      About to get CanSync property
15:06:32.374 CanSync                             OK       True
15:06:32.375 CanSyncAltAz                                 About to get CanSyncAltAz property
15:06:32.381 CanSyncAltAz                        OK       True
15:06:32.388 CanUnPark                                    About to get CanUnPark property
15:06:32.395 CanUnPark                           OK       False
15:06:32.396 
15:06:32.397 Pre-run Checks
15:06:32.405 Mount Safety                                 About to get AtPark property
15:06:32.422 Mount Safety                        INFO     Scope is not parked, continuing testing
15:06:32.426 TimeCheck                           INFO     PC Time Zone:  (UTC+01:00) Brussels, Copenhagen, Madrid, Paris offset: 1 hours.
15:06:32.428 TimeCheck                           INFO     PC UTCDate:    17-Feb-2024 14:06:32.426
15:06:32.438 TimeCheck                                    About to get UTCDate property
15:06:32.459 TimeCheck                           INFO     Mount UTCDate: 17-Feb-2024 14:06:31.000
15:06:32.460 
15:06:32.461 Properties
15:06:32.499 TargetDeclination Read                       About to get TargetDeclination property
15:06:32.522 TargetRightAscension Read                    About to get TargetRightAscension property
15:06:32.532 AlignmentMode                                About to get AlignmentMode property
15:06:32.542 AlignmentMode                       OK       GermanPolar
15:06:32.546 Altitude                                     About to get Altitude property
15:06:32.575 Altitude                            OK       +69:48:57.0
15:06:32.577 ApertureArea                                 About to get ApertureArea property
15:06:32.593 ApertureArea                        OK       Optional member returned a PropertyNotImplementedException (COM Error: 0x80040400) error.
15:06:32.628 ApertureDiameter                             About to get ApertureDiameter property
15:06:32.638 ApertureDiameter                    OK       Optional member returned a PropertyNotImplementedException (COM Error: 0x80040400) error.
15:06:32.640 AtHome                                       About to get AtHome property
15:06:32.648 AtHome                              OK       False
15:06:32.655 AtPark                                       About to get AtPark property
15:06:32.661 AtPark                              OK       False
15:06:32.665 Azimuth                                      About to get Azimuth property
15:06:32.677 Azimuth                             OK       +140:32:19.0
15:06:32.684 Declination                                  About to get Declination property
15:06:32.697 Declination                         OK       +30:34:40.2
15:06:32.698 DeclinationRate Read                         About to get DeclinationRate property
15:06:32.713 DeclinationRate Read                OK       0.00
15:06:32.720 DeclinationRate Write                        About to set DeclinationRate property to 0.0
15:06:32.741 DeclinationRate Write               OK       CanSetDeclinationRate is False and a PropertyNotImplementedException (COM Error: 0x80040400) error was generated as expected
15:06:32.743 DoesRefraction Read                          About to DoesRefraction get property
15:06:32.770 DoesRefraction Read                 OK       True
15:06:32.771 DoesRefraction Write                         About to set DoesRefraction property false
15:06:32.786 DoesRefraction Write                OK       Can set DoesRefraction to False
15:06:32.787 EquatorialSystem                             About to get EquatorialSystem property
15:06:32.805 EquatorialSystem                    OK       Topocentric
15:06:32.812 FocalLength                                  About to get FocalLength property
15:06:32.824 FocalLength                         OK       Optional member returned a PropertyNotImplementedException (COM Error: 0x80040400) error.
15:06:32.825 GuideRateDeclination Read                    About to get GuideRateDeclination property
15:06:32.839 GuideRateDeclination Read           OK       0.00
15:06:32.839 GuideRateDeclination Write                   About to set GuideRateDeclination property to 0.004178074605555556
15:06:32.848 GuideRateDeclination Write          OK       CanSetGuideRates is False and a PropertyNotImplementedException (COM Error: 0x80040400) error was generated as expected
15:06:32.858 GuideRateRightAscension Read                 About to get GuideRateRightAscension property
15:06:32.871 GuideRateRightAscension Read        OK       0.00
15:06:32.876 GuideRateRightAscension Write                About to set GuideRateRightAscension property to 0.004178074605555556
15:06:32.897 GuideRateRightAscension Write       OK       CanSetGuideRates is False and a PropertyNotImplementedException (COM Error: 0x80040400) error was generated as expected
15:06:32.903 IsPulseGuiding                               About to get IsPulseGuiding property
15:06:32.917 IsPulseGuiding                      OK       CanPulseGuide is False and a PropertyNotImplementedException (COM Error: 0x80040400) error was generated as expected
15:06:32.923 RightAscension                               About to get RightAscension property
15:06:32.942 RightAscension                      OK       +00:43:52.97
15:06:32.943 RightAscensionRate Read                      About to get RightAscensionRate property
15:06:32.950 RightAscensionRate Read             OK       0.00
15:06:32.952 RightAscensionRate Write                     About to set RightAscensionRate property to 0.00
15:06:32.965 RightAscensionRate Write            OK       CanSetRightAscensionRate is False and a PropertyNotImplementedException (COM Error: 0x80040400) error was generated as expected
15:06:32.972 SiteElevation Read                           About to get SiteElevation property
15:06:33.009 SiteElevation Read                  OK       10
15:06:33.010 SiteElevation Write                          About to set SiteElevation property to -301.0
15:06:33.031 SiteElevation Write                 OK       Invalid Value exception generated as expected on set site elevation < -300m
15:06:33.042 SiteElevation Write                          About to set SiteElevation property to 100001.0
15:06:33.063 SiteElevation Write                 OK       Invalid Value exception generated as expected on set site elevation > 10,000m
15:06:33.072 SiteElevation Write                          About to set SiteElevation property to 10
15:06:33.089 SiteElevation Write                 OK       Current value 10m written successfully
15:06:33.090 SiteLatitude Read                            About to get SiteLatitude property
15:06:33.112 SiteLatitude Read                   OK       +47:16:37.0
15:06:33.120 SiteLatitude Write                           About to set SiteLatitude property to -91.0
15:06:33.141 SiteLatitude Write                  OK       Invalid Value exception generated as expected on set site latitude < -90 degrees
15:06:33.142 SiteLatitude Write                           About to set SiteLatitude property to 91.0
15:06:33.145 SiteLatitude Write                  OK       Invalid Value exception generated as expected on set site latitude > 90 degrees
15:06:33.146 SiteLatitude Write                           About to set SiteLatitude property to 47.276944444444446
15:06:33.179 SiteLatitude Write                  OK       Current value: +47:16:37.0 degrees written successfully
15:06:33.193 SiteLongitude Read                           About to get SiteLongitude property
15:06:33.208 SiteLongitude Read                  OK       -02:28:44.0
15:06:33.225 SiteLongitude Write                          About to set SiteLongitude property to -181.0
15:06:33.244 SiteLongitude Write                 OK       Invalid Value exception generated as expected on set site longitude < -180 degrees
15:06:33.245 SiteLongitude Write                          About to set SiteLongitude property to 181.0
15:06:33.258 SiteLongitude Write                 OK       Invalid Value exception generated as expected on set site longitude > 180 degrees
15:06:33.263 SiteLongitude Write                          About to set SiteLongitude property to -2.478888888888889
15:06:33.290 SiteLongitude Write                 OK       Current value -02:28:44.0 degrees written successfully
15:06:33.291 Slewing                                      About to get Slewing property
15:06:33.309 Slewing                             OK       False
15:06:33.315 SlewSettleTime Read                          About to get SlewSettleTime property
15:06:33.343 SlewSettleTime Read                 OK       0
15:06:33.345 SlewSettleTime Write                         About to set SlewSettleTime property to -1
15:06:33.361 SlewSettleTime Write                OK       Invalid Value exception generated as expected on set slew settle time < 0
15:06:33.362 SlewSettleTime Write                         About to set SlewSettleTime property to 0
15:06:33.376 SlewSettleTime Write                OK       Legal value 0 seconds written successfully
15:06:33.381 SideOfPier Read                              About to get SideOfPier property
15:06:33.398 SideOfPier Read                     OK       Normal
15:06:33.406 SiderealTime                                 About to get SiderealTime property
15:06:33.423 SiderealTime                        OK       +23:44:50.73
15:06:33.428 SiderealTime                        OK       Scope and ASCOM sidereal times agree to better than 2 seconds, Scope: +23:44:50.73, ASCOM: +23:44:52.28
15:06:33.435 TargetDeclination Read              OK       Not Set exception generated on read before write
15:06:33.441 TargetDeclination Write             INFO     Tests moved after the SlewToCoordinates tests so that Conform can confirm that target coordinates are set as expected.
15:06:33.441 TargetRightAscension Read           OK       Not Set exception generated on read before write
15:06:33.447 TargetRightAscension Write          INFO     Tests moved after the SlewToCoordinates tests so that Conform can confirm that target coordinates are set as expected.
15:06:33.448 Tracking Read                                About to get Tracking property
15:06:33.471 Tracking Read                       OK       False
15:06:33.476 Tracking Write                               About to set Tracking property true
15:06:33.486 Tracking Write                      OK       CanSetTracking is False and a PropertyNotImplementedException (COM Error: 0x80040400) error was generated as expected
15:06:33.488 TrackingRates                                About to get TrackingRates property
15:06:33.514 TrackingRates                                About to get TrackingRates property
15:06:33.525 TrackingRates                                Found drive rate: Sidereal
15:06:33.531 TrackingRates                                Found drive rate: Solar
15:06:33.537 TrackingRates                                Found drive rate: Lunar
15:06:33.542 TrackingRates                       OK       Drive rates read OK
15:06:33.548 TrackingRates                       OK       Disposed tracking rates OK
15:06:33.558 TrackingRates                                About to get TrackingRates property
15:06:33.560 TrackingRates                       OK       Successfully obtained a TrackingRates object after the previous TrackingRates object was disposed
15:06:33.561 TrackingRate Read                            About to get TrackingRate property
15:06:33.593 TrackingRate Read                   OK       Sidereal
15:06:33.606 TrackingRate Write                           About to set TrackingRate property to Sidereal
15:06:33.623 TrackingRate Write                  OK       Successfully set drive rate: Sidereal
15:06:33.624 TrackingRate Write                           About to set TrackingRate property to Solar
15:06:33.639 TrackingRate Write                  OK       Successfully set drive rate: Solar
15:06:33.645 TrackingRate Write                           About to set TrackingRate property to Lunar
15:06:33.658 TrackingRate Write                  OK       Successfully set drive rate: Lunar
15:06:33.660 TrackingRate Write                           About to set TrackingRate property to invalid value (5)
15:06:33.672 TrackingRate Write                  OK       Invalid Value exception generated as expected when TrackingRate is set to an invalid value (5)
15:06:33.673 TrackingRate Write                           About to set TrackingRate property to invalid value (-1)
15:06:33.682 TrackingRate Write                  OK       Invalid Value exception generated as expected when TrackingRate is set to an invalid value (-1)
15:06:33.711 TrackingRate Write                           About to set TrackingRate property to Sidereal
15:06:33.722 UTCDate Read                                 About to get UTCDate property
15:06:33.737 UTCDate Read                        OK       17-Feb-2024 14:06:32.000
15:06:33.739 UTCDate Write                                About to set UTCDate property to 17/02/2024 3:06:32 pm
15:06:33.752 UTCDate Write                       OK       New UTCDate written successfully: 17/02/2024 3:06:32 pm
15:06:33.758 UTCDate Write                                About to set UTCDate property to 17/02/2024 2:06:32 pm
15:06:33.770 UTCDate Write                       OK       Original UTCDate restored successfully: 17/02/2024 2:06:32 pm
15:06:33.771 
15:06:33.772 Methods
15:06:33.789 CanMoveAxis:Primary                          About to call CanMoveAxis method 0
15:06:33.822 CanMoveAxis:Primary                 OK       CanMoveAxis:Primary False
15:06:33.823 CanMoveAxis:Secondary                        About to call CanMoveAxis method 1
15:06:33.826 CanMoveAxis:Secondary               OK       CanMoveAxis:Secondary False
15:06:33.841 CanMoveAxis:Tertiary                         About to call CanMoveAxis method 2
15:06:33.842 CanMoveAxis:Tertiary                OK       CanMoveAxis:Tertiary False
15:06:33.842 Park                                         About to Park call method
15:06:33.875 Park                                OK       CanPark is False and a MethodNotImplementedException (COM Error: 0x80040400) error was generated as expected
15:06:33.883 UnPark                                       About to call UnPark method
15:06:33.904 UnPark                              OK       CanUnPark is False and a MethodNotImplementedException (COM Error: 0x80040400) error was generated as expected
15:06:33.919 AbortSlew                                    About to call AbortSlew method
15:06:33.945 AbortSlew                           ISSUE    AbortSlew Exception
System.Runtime.InteropServices.COMException (0x8004040C): Unknown  Action is not implemented in this driver.
   at Microsoft.CSharp.RuntimeBinder.ComInterop.ComRuntimeHelpers.CheckThrowException(Int32 hresult, ExcepInfo& excepInfo, UInt32 argErr, String message)
   at CallSite.Target(Closure, CallSite, ComObject)
   at System.Dynamic.UpdateDelegates.UpdateAndExecute1[T0,TRet](CallSite site, T0 arg0)
   at CallSite.Target(Closure, CallSite, Object)
   at System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid1[T0](CallSite site, T0 arg0)
   at ConformU.TelescopeFacade.<AbortSlew>b__108_0() in J:\ConformU\ConformU\Conform\Devices\Facades\TelescopeFacade.cs:line 293
   at ConformU.DriverHostForm.ActionNoParameters(Action action) in J:\ConformU\ConformU\Conform\Devices\Facades\BaseClass\DriverHostForm.cs:line 163
   at ConformU.FacadeBaseClass.<>c__DisplayClass11_0.<MethodNoParameters>b__0() in J:\ConformU\ConformU\Conform\Devices\Facades\BaseClass\FacadeBaseClass.cs:line 230
   at System.Windows.Forms.Control.InvokeMarshaledCallbackHelper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Forms.Control.InvokeMarshaledCallbacks()
--- End of stack trace from previous location ---
   at System.Windows.Forms.Control.MarshaledInvoke(Control caller, Delegate method, Object[] args, Boolean synchronous)
   at System.Windows.Forms.Control.Invoke(Delegate method, Object[] args)
   at System.Windows.Forms.Control.Invoke(Action method)
   at ConformU.FacadeBaseClass.MethodNoParameters(Action action) in J:\ConformU\ConformU\Conform\Devices\Facades\BaseClass\FacadeBaseClass.cs:line 230
   at ConformU.TelescopeFacade.AbortSlew() in J:\ConformU\ConformU\Conform\Devices\Facades\TelescopeFacade.cs:line 293
   at ConformU.TelescopeTester.AbortSlew(String testName) in J:\ConformU\ConformU\Conform\Devices\TelescopeTester.cs:line 8259
   at ConformU.TelescopeTester.TelescopeOptionalMethodsTest(OptionalMethodType testType, String testName, Boolean canTest) in J:\ConformU\ConformU\Conform\Devices\TelescopeTester.cs:line 5687
15:06:33.946 AbortSlew                           ISSUE    Unexpected error: Unknown  Action is not implemented in this driver.

I **_expected to get here an ok_**

**Comment by Peter-Simpson** [comment]
Hi Charles,

Apologies for the long delay in replying, I lost track of this issue. I think there are two issues here: 

1. Your AbortSlew method is throwing an ASCOM.ActionNotimplementedException instead of the expected ASCOM.MethodNotimplementedException.
2. There is a Conform bug that you haven't come across yet where Conform won't accept ASCOM.MethodNotImplementedException as a valid response to AbortSlew().

A fix for 2. will be in the next Conform Universal release.

Thanks for reporting the issue.

Best wishes, Peter

**Comment by Peter-Simpson** [comment]
Closing because the fixed version has been released.
