### ISSUE TITLE
Value checks trigger even on error responses

### ISSUE THREAD

**Issue by RReverser** [Peter-Simpson/ConformU#16]
Latest ConformU "Check Alpaca Protocol" is returning new errors that I believe I haven't seen in the past on my driver. They all look like this, for various unimplemented properties:

```
11:38:53.118 GET CCDTemperature            ISSUE  A JSON parameter of name Value was expected, but was not found in the JSON response. This test is case sensitive.
11:38:53.119 GET CCDTemperature                     Response: {"ClientTransactionID":67890,"ServerTransactionID":3553,"ErrorNumber":1024,"ErrorMessage":"Property or method not implemented"}
```

Is `Value` field really necessary even on error responses? I could set it to some dummy value, but it seems useless - if anything, I'd expect the tests to check that it's _never_ present on error responses?

**Comment by Peter-Simpson** [comment]
Hi Ingvar,

 

A couple of people have remarked on this behaviour, so I’ve just updated ConformU not to report missing Value parameters when the device reports an error and Conform is in its tolerant (default) Alpaca protocol check mode. You just need to make sure that the Alpaca Settings strict check flag is unset as shown below.

 

Here is a new installer, please can you let me know if it fixes the issue? https://download.ascom-standards.org/beta/ConformU(3.0.0+30860)Setup.exe 

 

Best wishes, Peter

**Comment by RReverser** [comment]
> Here is a new installer, please can you let me know if it fixes the issue? [download.ascom-standards.org/beta/ConformU(3.0.0+30860)Setup.exe](https://download.ascom-standards.org/beta/ConformU(3.0.0+30860)Setup.exe)

Thanks, it does.

**Comment by Peter-Simpson** [comment]
Great, thanks for confirming!

Best wishes, Peter
