### ISSUE TITLE
Command line options in README is out of date

### ISSUE THREAD

**Issue by RReverser** [Peter-Simpson/ConformU#18]
README currently says:

> - '--commandline' - Run as a command line application with no graphical interface using a pre-configured settings file.
> - '--settings fullyqualifiedfilename' - Fully qualified file name of the application configuration file. Leave blank to use the default location.
> - '--logfilepath fullyqualifiedlogfilepath' - Fully qualified path to the log file folder. Leave blank to use the default mechanic, which creates a new folder each day,
> - '--logfile filename' - If filename has no directory/folder component it will be appended to the log file path to create the fully qualified log file name. If filename is fully qualified, any logfilepath parameter will be ignored. Leave filename blank to use automatic file naming, where the file name will be based on the file creation time.
> - '--resultsfile fullyqualifiedfilename' - Fully qualified file name of the results file.
> - '--debugdiscovery' - Write discovery debug information to the log.
> - '--debugstartup' - Write start-up debug information to the log.
> - '--help' - Display a help screen.
> - '--version' - Display version information.

However, when trying to run conformu with e.g. `--commandline`, you'll get:

```
Unrecognized command or argument '--commandline'.

Description:
  Conform Universal 3.1.0 (Build 31181.cb32ac3)
  Copyright (c) 2021-2024 Peter Simpson

  Enter conformu [command] -h for information on options available in each command.

  If no command or options are provided Conform Universal will start as a GUI application using default parameters.

Usage:
  conformu [command] [options]

Options:
  -v, --version   Show the Conform Universal version number
  -?, -h, --help  Show help and usage information

Commands:
  conformance <COM_PROGID_or_ALPACA_URI>  Check the specified device for ASCOM device interface conformance with all tests enabled.     
  alpacaprotocol <Alpaca_URI>             Check the specified Alpaca device for Alpaca protocol conformance
  conformance-settings                    Check the device configured in the settings file for ASCOM device interface conformance       
  alpacaprotocol-settings                 Check the device configured in the settings file for Alpaca protocol conformance
  gui                                     Start Conform Universal as a GUI application with options to change the log file, results     
                                          file and settings file locations
```

**Comment by Peter-Simpson** [comment]
Thanks for letting me know, I've updated the README and ConformU Help sections with current command line parameters.
