### ISSUE TITLE
ConformU doesn't accept URLs with hostname

### ISSUE THREAD

**Issue by RReverser** [Peter-Simpson/ConformU#23]
The CLI docs say:

> $ ~/conformu/conformu alpacaprotocol --help
> Description:
>   Check the specified Alpaca device for Alpaca protocol conformance
> 
> Usage:
>   conformu alpacaprotocol <Alpaca_URI> [options]
> 
> Arguments:
>   <Alpaca_URI>  The device's Alpaca URI (e.g. http://host:port/api/v1/[DeviceType]/[DeviceNumber]).
>                 The ASCOM device type will be inferred from the supplied URI.

However, counter-intuitively, trying to pass a URL with host fails:

```
$ ~/conformu/conformu alpacaprotocol http://localhost:32323/api/v1/telescope/0

Unable to identify the device identifier as either a COM ProgID or an Alpaca URI. Is there a typo in the device identifier?

The Alpaca URI argument is invalid:
```

It seems only passing IP address (127.0.0.1 in this case) is supported, but both should probably be accepted.

**Comment by Peter-Simpson** [comment]
Hi Ingvar, I've fixed #23 and #24. Can you let me know which Linux flavour you are using so I can send you a build to test? The options are x64, arm32 and arm64, thanks, Peter

**Comment by RReverser** [comment]
That's okay, I can just use `dotnet run` from the latest commit. I'll try tomorrow.

**Comment by RReverser** [comment]
Thanks, latest commit works as expected now.

**Comment by Peter-Simpson** [comment]
Great, thanks for letting me know.

**Comment by RReverser** [comment]
Can you publish 4.0.1 please?

**Comment by Peter-Simpson** [comment]
I’ve just published 4.1.0. 

 

Best wishes, Peter

**Comment by RReverser** [comment]
Ah thanks. I think from semver point of view, a patch version here would be enough, since those are just bugfixes, but either one is fine :)

**Comment by RReverser** [comment]
For now used in the simulators project: https://github.com/ASCOMInitiative/ASCOM.Alpaca.Simulators/pull/34

Looking good and useful: https://github.com/RReverser/ASCOM.Alpaca.Simulators/actions/runs/12379069796/job/34552397380#step:7:135

**Comment by Peter-Simpson** [comment]
I'm glad it's working well in your CI checks, thanks for letting me know!

I'm surprised the OmniSim CameraState property reports "Download" state rather than "Idle" state at startup, which is why the AbortExposure test fails later in the results. I've never seen that in my use of the OmniSim to date, and it doesn't appear in the Windows version of 0.4.1-rc.1.

**Comment by RReverser** [comment]
Yeah it seems there are couple of devices with issues in latest omnisim from git. Haven't seen them in the past either, but then, both Conform and Omnisim have changed meanwhile. https://github.com/ASCOMInitiative/ASCOM.Alpaca.Simulators/issues/33

**Comment by RReverser** [comment]
Hmm, actually... maybe that particular issue is due to `conformu alpacaprotocol ...` leaving the device in "dirty" state?

It seems AlpacaProtocolTestManager is testing the `ImageArray` property, which I guess could trigger a download instead of pure property access in the simulator? Just a guess though.

But even then, I'm not sure if it's a bug in the simulators as GET property access isn't supposed to change the state, or a bug in ConformU...

**Comment by Peter-Simpson** [comment]
Can you try re-ordering the tests so the Conformance test runs before the Alpaca protocol test? If that works it would reinforce your suggestion about Alpaca protocol leaving the device in a dirty state.

**Comment by RReverser** [comment]
Looks like that's it, it does pass the other way around: https://github.com/RReverser/ASCOM.Alpaca.Simulators/actions/runs/12413108501/job/34654290737

So now the question is only where the bug is...

**Comment by RReverser** [comment]
I guess, as a separate question, why are those distinct test groups anyway? I'd expect a single command like `conformu http://...` would always run all tests (both Alpaca and Conformance tests together), which would also guarantee they don't conflict with each other.

I understand that conformance tests are a bit more universal, since they applie to COM devices as well, but if a device is detected to be Alpaca one (given a URL), I think there is no harm in just running everything?

**Comment by RReverser** [comment]
> So now the question is only where the bug is...

Ah, it's right here:

https://github.com/ASCOMInitiative/ConformU/blob/5571b361c6014c673b4f3c7a9e9a57a60050a96c/ConformU/AlpacaProtocolTestManager.cs#L619-L622

this is only waiting for the exposing state to change, without accounting for the Download one. I'm going to send a PR.

**Comment by Peter-Simpson** [comment]
I've committed some wait logic so the Alpaca protocol camera check will only exit with one of the two long-term camera states: Idle or Error, this should fix the ordering issue.

**Comment by RReverser** [comment]
Thank you.
